USE [AdventureWorks2017]
GO

/****** Object:  Table [dbo].[Vente]    Script Date: 07/03/2023 13:31:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Vente](
	[ID] [uniqueidentifier] NOT NULL,
	[Libelle] [nvarchar](max) NOT NULL,
	[Prix] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_Vente] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


